# Generated by Django 2.0 on 2019-06-12 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('recipeid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Restrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('dietid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=500)),
                ('receivedate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Quantities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('deliveryid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dietary_Restrictions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('credit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Quantities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('orderid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('placedate', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('pickupid', models.IntegerField()),
                ('recieved_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('priceper', models.IntegerField()),
                ('perunit', models.CharField(max_length=50)),
                ('aisle', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=500)),
                ('iconid', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('searchitem', models.CharField(max_length=50)),
                ('searchstrength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.IntegerField()),
                ('tagid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
                ('createdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('img', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('usertype', models.IntegerField()),
                ('createdate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
