# Generated by Django 2.0 on 2019-06-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Recipes',
            new_name='CustomerRecipes',
        ),
        migrations.RenameModel(
            old_name='Customer_Restrictions',
            new_name='CustomerRestrictions',
        ),
        migrations.RenameModel(
            old_name='Delivery_Quantities',
            new_name='DeliveryQuantities',
        ),
        migrations.RenameModel(
            old_name='Dietary_Restrictions',
            new_name='DietaryRestrictions',
        ),
        migrations.RenameModel(
            old_name='Order_Quantities',
            new_name='OrderQuantities',
        ),
    ]
