# Generated by Django 2.0 on 2019-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=20)),
                ('admintype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('createdate', models.CharField(max_length=20)),
            ],
        ),
    ]
