# Generated by Django 2.0 on 2019-06-12 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='createdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='admin',
            name='secret',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
