# Generated by Django 2.0 on 2019-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20190612_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='createdate',
            field=models.CharField(max_length=200),
        ),
    ]
